---
- name: Zabbix test rulebookgrim
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Run playbook for hosts that have a change in installed package
      condition: event.payload.event_name is select ("==","Number of installed packages has been changed")
      action:
        run_job_template:
          name: "Run Shutdown"
          organization: "Default"
          job_args:
            extra_vars:
              problem_hosts: "{{ event.payload.host_host }}"

    - name: Run playbook for hosts that have critically low disk space
      condition: event.payload.trigger_id == 24757
      action:
        run_job_template:
          name: "Low Diskspace"
          organization: "Bobit.local"
          job_args:
            extra_vars:
              low_diskspace_host: "{{ event.payload.host_host }}"
              low_diskspace_os: "{{ event.payload.target }}
...
