---
- name: Zabbix test rulebookgrim
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Run playbook for hosts that have critically low disk space
      condition: event.payload.trigger_id is select ("==",24757)
      action:
        run_job_template:
          name: "Linux Low Diskspace"
          organization: "bobit.local"
          job_args:
            extra_vars:
              low_diskspace_host: "{{ event.payload.host_host }}"


    - name: Run playbook for important port that went down
      condition: event.payload.trigger_id is select ("==",25577)
      action:
        run_job_template:
          name: "No shutdown on port"
          organization: "bobit.local"
          job_args:
            extra_vars:
              network_device: "{{ event.payload.host_host }}"
              network_port: "{{ event.payload.event_tags.interface[0] }}"

...
