---
- name: Addition of harddisk space to vm
  hosts: DKTON01CENT01
  become: true
  vars:
    ansible_become_pass: password
  gather_facts: false
  tasks:
    - name: Read device information (always use unit when probing)
      community.general.parted: device=/dev/sda unit=MiB
      register: sda_info
      
    - debug:
        msg: "{{ sda_info }}"
        
    - name: Extend an existing partition to fill all available space
      community.general.parted:
        device: /dev/sda
        number: "{{ sda_info.partitions | length }}"
        part_end: "100%"
        resize: true
        state: present
        
    - debug:
        msg: "{{ ansible_mounts }}"" 
        
    - name: Collect only facts about hardware
      setup:
        gather_subset:
        - hardware

    - name: Output disks
      debug:
        var: hostvars[inventory_hostname].ansible_devices.keys() | list
