---
- name: Addition of harddisk space to vm
  become: true
  vars:
    ansible_become_pass: Pa55w.rd
  hosts: "{{ low_diskspace_host }}"
  gather_facts: true
  tasks:
    -  name: Resize VM Disk
       community.general.proxmox_disk:
         api_host: "{{ proxmox_node }}"
         api_user: root@pam
         api_password: Pa55w.rd
         vmid: "{{ proxmox_vmid }}"
         disk: scsi0
         size: +5G
         state: resized
...


"{{ low_diskspace_host }}"
