---
- name: Addition of harddisk space to vm
  hosts: DKTON01ZAB01
  gather_facts: false
  tasks:
    -  name: Resize VM Disk
       community.general.proxmox_disk:
         api_host: 10.131.9.120
         api_user: zabbix@pam
         api_token_id: zabbixpermission
         api_token_secret: 8db143c0-52e8-4f13-9d85-cb150f5c852c
         name: "{{ low_diskspace_host }}"
         disk: scsi0
         size: +5G
         state: resized

- name: Resize the correct disk within the VM
  hosts: "{{ low_diskspace_host }}"
  gather_facts: false
  tasks:
    - name: Register partition info
      community.general.parted: device=/dev/sdb unit=MiB
      register: sdb_info
      
    - name: Extend an existing partition to fill all available space
        community.general.parted:
        device: /dev/sdb
        number: "{{ sdb_info.partitions | length }}"
        part_end: "100%"
        resize: true
        state: present
      when: sdb_info.partiting | length == {{payload size ????}}
...
