---
- name: Addition of harddisk space to vm
  hosts: DKTON01ZAB01
  gather_facts: true
  tasks:
    -  name: Resize VM Disk
       community.general.proxmox_disk:
         api_host: DKTON01PVE01
         api_user: zabbix@pam
         api_token_id: zabbix@pam!zabbixpermission
         api_token_secret: 8db143c0-52e8-4f13-9d85-cb150f5c852c
         password: Pa55w.rd
         name: "{{ low_diskspace_host }}"
         disk: scsi0
         size: +5G
         state: resized
...
