---
- name: Addition of harddisk space to vm
  hosts: "{{ low_diskspace_host }}"
  gather_facts: false
  tasks:
    -  name: Resize VM Disk
       community.general.proxmox_disk:
         api_host: 10.131.9.120
         api_user: zabbix@pam
         api_token_id: zabbixpermission
         api_token_secret: 8db143c0-52e8-4f13-9d85-cb150f5c852c
         name: "{{ low_diskspace_host }}"
         disk: scsi0
         size: +5G
         state: resized
...
