---
- name: Addition of harddisk space to vm
  hosts: DKTON01ZAB01
  gather_facts: false
  tasks:
    -  name: Resize VM Disk
       community.general.proxmox_disk:
         api_host: 10.131.9.120
         api_user: zabbix@pam
         api_token_id: zabbixpermission
         api_token_secret: 8db143c0-52e8-4f13-9d85-cb150f5c852c
         name: "{{ low_diskspace_host }}"
         disk: scsi0
         size: +5G
         state: resized

- name: Disk changes on problem host
  hosts: "{{ low_diskspace_host }}"
  become: true
  vars:
    ansible_become_pass: password
  gather_facts: true
  tasks:
  
    - name: Read device information (always use unit when probing)
      community.general.parted: device=/dev/sda unit=MiB
      register: disk_info

    - name: Extend an existing partition to fill all available space
      community.general.parted:
        device: /dev/sda
        number: "{{ disk_info.partitions | length }}"
        part_end: "100%"
        resize: true
        state: present

    - name: Resize existing pv
      community.general.lvg:
        vg: "{{ ansible_lvm.lvs[low_filesystem].vg }}"
        pvs: /dev/sda2
        pvresize: yes 
        
    - name: Regather facts for disk updates
      setup:
        filter:
          - 'ansible_mount'
          - 'ansible_lvm'
           
    - name: Extend the logical volume to take all remaining space of the PVs and resize the underlying filesystem
      community.general.lvol:
        vg: "{{ ansible_lvm.lvs[low_filesystem].vg }}"
        lv: "{{ low_filesystem }}"
        size: 100%FREE
        resizefs: true
...
