---
- name: Addition of harddisk space to vm
  hosts: dkton01awx01
  gather_facts: true
  tasks:
    -  name: Resize VM Disk
       community.general.proxmox_disk:
         api_host: DKTON01PVE01
         api_user: root@pam
         api_password: Pa55w.rd
         name: "{{ low_diskspace_host }}"
         disk: scsi0
         size: +5G
         state: resized
...
