---
- name: Addition of harddisk space to vm
  hosts: DKTON01CENT01
  gather_facts: false
  tasks:
    - name: Read device information (always use unit when probing)
      community.general.parted: device=/dev/sda unit=MiB
      register: sda_info
