---
- name: Enable Switch Port
  hosts: "{{ network_device }}"
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Enable the interface
      cisco.ios.ios_interfaces:
        config:
          name: "{{ network_port }}"
          enabled: true
        state: merged
...
